

CREATE TABLE IF NOT EXISTS `DATASOURCE` (
  `ID` int(6) NOT NULL AUTO_INCREMENT,
  `ALIAS` varchar(64) DEFAULT NULL,
  `NAME` varchar(128) NOT NULL,
  `TYPE` varchar(64) DEFAULT NULL,
  `DRIVER` varchar(64) NOT NULL,
  `URL` varchar(128) NOT NULL,
  `USERNAME` varchar(32) NOT NULL,
  `PASSWORD` varchar(32) DEFAULT NULL,
  `INITIAL_SIZE` int(2) DEFAULT '2',
  `MIN_IDLE` int(2) DEFAULT '1',
  `MAX_IDLE` int(2) DEFAULT '20',
  `MAX_ACTIVE` int(2) DEFAULT '20',
  `MAX_WAIT` int(6) DEFAULT '6000',
  `TIME_BET_EVI_RUNS_MILLIS` int(6) DEFAULT '6000',
  `VALIDATION_QUERY` varchar(256) DEFAULT 'SELECT 1',
  `TEST_WHILE_IDLE` tinyint(1) DEFAULT '1',
  `POOL_PREPARED_STATEMENTS` tinyint(1) DEFAULT '1',
  `MAX_POOL_PER_CONNS` int(4) DEFAULT '20',
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `STATEMENT` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `ALIAS` varchar(64) DEFAULT NULL,
  `SQL_STRING` text NOT NULL,
  `TYPE` varchar(10) NOT NULL DEFAULT 'select',
  `CATEGORY` varchar(64) DEFAULT NULL,
  `RESULT_TYPE` varchar(10) NOT NULL DEFAULT 'HashMap',
  PRIMARY KEY (`ID`)
);